### ISSUE TITLE
Error with A25 module

### ISSUE THREAD

**Issue by antserran** [echicken/kiss-tnc#1]
When I try the given example, I get the following error: 

(node:11119) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'control' of undefined

The error seems to be here: 

function send_string(str) {
    const packet = new AX25.Packet();
    packet.type = AX25.Masks.control.frame_types.u_frame.subtypes.ui; -------------------------------> HERE
    packet.source = { callsign : 'VE3XEC', ssid : 0 };
    packet.destination = { callsign : 'CQ', ssid : 0 };
    packet.payload = Buffer.from(str, 'ascii');
    tnc.send_data(packet.assemble(), () => console.log('Sent:', str));
}

Any idea?

**Comment by echicken** [comment]
That example code will not work with what's in the 'master' branch of my node-ax25 repository (or with the module currently published on NPM).  You can try it with the 'es6rewrite' branch of node-ax25:

https://github.com/echicken/node-ax25/tree/es6rewrite

That branch is incomplete.  You could use it for APRS and things of that nature, but not any full AX.25 sessions with flow control, error correction, etc.

Also, if the code you pasted is what you actually tried to run, please remember to alter the 'packet.source.callsign' property before transmitting.

**Comment by antserran** [comment]
That was the problem!
I fixed it and now it is working as expected,

thank you really much for answering!
